version: "3.8"

services:

  web-mvc:
    image: nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports: 
      - "5001:5001"
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://*:5001
      # - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_ENVIRONMENT=Production
          
