version: "3.8"

services:
  sql-server:
    image: nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  # Image/Container - Web-mvc front
  web-mvc:
    image: nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://*:5001
      # - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_ENVIRONMENT=Production

  # Image/Container - API Identidade
  api-identidade:
    image: nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/NSE.Identidade.API/Dockerfile
    ports:
      - "5101:5101"
    environment:
      - ASPNETCORE_URLS=http://*:5101
      # - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_ENVIRONMENT=Production
